### ISSUE TITLE
Case details are not displayed 

### ISSUE THREAD

**Issue by cadmiumcat** [ONSdigital/Blaise_Survey_Manager#69]
After doing a respondent search and clicking on Case Details, the following error appears: 
![image](https://user-images.githubusercontent.com/52242161/63853380-76f9c780-c992-11e9-92d3-6270feffb5e3.png)

**Comment by martyncolmer** [comment]
You need to start using the MSSQL data base now and not the MYSQL.
The MYSQL tables are no longer matinainted.

**Comment by cadmiumcat** [comment]
README.md needs updating to refer to new repo and give proper instructions
